In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import json
from pathlib import Path

# EDIT THIS PATH
DATASET_ROOT = Path("/content/drive/MyDrive/dataset")

print("Exists:", DATASET_ROOT.exists())
print("Root:", DATASET_ROOT)
print("Items:", [p.name for p in DATASET_ROOT.iterdir()] if DATASET_ROOT.exists() else "Path not found")

Exists: True
Root: /content/drive/MyDrive/dataset
Items: ['metadata.csv', 'hf_voice_dataset']

In [ ]:
import os
import json
from pathlib import Path

# EDIT THIS PATH
DATASET_ROOT = Path("/content/drive/MyDrive/dataset/hf_voice_dataset")

print("Exists:", DATASET_ROOT.exists())
print("Root:", DATASET_ROOT)
print("Items:", [p.name for p in DATASET_ROOT.iterdir()] if DATASET_ROOT.exists() else "Path not found")

Exists: True
Root: /content/drive/MyDrive/dataset/hf_voice_dataset
Items: ['dataset_dict.json', 'train', 'validation']

In [ ]:
import os
import json
from pathlib import Path

# EDIT THIS PATH
DATASET_ROOT = Path("/content/drive/MyDrive/dataset/hf_voice_dataset/train")

print("Exists:", DATASET_ROOT.exists())
print("Root:", DATASET_ROOT)
print("Items:", [p.name for p in DATASET_ROOT.iterdir()] if DATASET_ROOT.exists() else "Path not found")

Exists: True
Root: /content/drive/MyDrive/dataset/hf_voice_dataset/train
Items: ['state.json', 'dataset_info.json', 'data-00000-of-00001.arrow']

In [ ]:
import os
import json
from pathlib import Path

# EDIT THIS PATH
DATASET_ROOT = Path("/content/drive/MyDrive/dataset/hf_voice_dataset/validation")

print("Exists:", DATASET_ROOT.exists())
print("Root:", DATASET_ROOT)
print("Items:", [p.name for p in DATASET_ROOT.iterdir()] if DATASET_ROOT.exists() else "Path not found")

Exists: True
Root: /content/drive/MyDrive/dataset/hf_voice_dataset/validation
Items: ['dataset_info.json', 'state.json', 'data-00000-of-00001.arrow']

In [ ]:
import json
from pathlib import Path
from datasets import load_from_disk

DATASET_ROOT = Path("/content/drive/MyDrive/dataset/hf_voice_dataset")

print("Exists:", DATASET_ROOT.exists())
print("Root:", DATASET_ROOT)

json_path = DATASET_ROOT / "dataset_dict.json"
print("dataset_dict.json exists:", json_path.exists())

if json_path.exists():
    with open(json_path, "r", encoding="utf-8") as f:
        dataset_info = json.load(f)
    print("\nTop-level type:", type(dataset_info))
    if isinstance(dataset_info, dict):
        print("Top-level keys:", list(dataset_info.keys()))

voice_ds = load_from_disk(str(DATASET_ROOT))

print("\nLoaded dataset:")
print(voice_ds)

print("\nAvailable splits:", list(voice_ds.keys()))

for split in voice_ds.keys():
    print(f"{split} size:", len(voice_ds[split]))

print("\nTrain columns:", voice_ds["train"].column_names)
print("\nFirst train sample:")
print(voice_ds["train"][0])

Exists: True
Root: /content/drive/MyDrive/dataset/hf_voice_dataset
dataset_dict.json exists: True

Top-level type: <class 'dict'>
Top-level keys: ['splits']

Loaded dataset:
DatasetDict({
    train: Dataset({
        features: ['audio', 'text'],
        num_rows: 60
    })
    validation: Dataset({
        features: ['audio', 'text'],
        num_rows: 11
    })
})

Available splits: ['train', 'validation']
train size: 60
validation size: 11

Train columns: ['audio', 'text']

First train sample:
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x77fffae96ed0>, 'text': 'أنا مش عايزة أبالغ في النطق'}

In [ ]:
!pip install -q datasets[audio] transformers evaluate jiwer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 59.2 MB/s eta 0:00:00

In [ ]:
from datasets import load_dataset

dataset = load_dataset("MAdel121/arabic-egy-cleaned")
dataset

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/28 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/28 [00:00<?, ?files/s]

data/train-00000-of-00028.parquet:   0%|          | 0.00/475M [00:00<?, ?B/s]

data/train-00001-of-00028.parquet:   0%|          | 0.00/466M [00:00<?, ?B/s]

data/train-00002-of-00028.parquet:   0%|          | 0.00/469M [00:00<?, ?B/s]

data/train-00003-of-00028.parquet:   0%|          | 0.00/474M [00:00<?, ?B/s]

data/train-00004-of-00028.parquet:   0%|          | 0.00/470M [00:00<?, ?B/s]

data/train-00005-of-00028.parquet:   0%|          | 0.00/470M [00:00<?, ?B/s]

data/train-00006-of-00028.parquet:   0%|          | 0.00/472M [00:00<?, ?B/s]

data/train-00007-of-00028.parquet:   0%|          | 0.00/480M [00:00<?, ?B/s]

data/train-00008-of-00028.parquet:   0%|          | 0.00/468M [00:00<?, ?B/s]

data/train-00009-of-00028.parquet:   0%|          | 0.00/469M [00:00<?, ?B/s]

data/train-00010-of-00028.parquet:   0%|          | 0.00/471M [00:00<?, ?B/s]

data/train-00011-of-00028.parquet:   0%|          | 0.00/471M [00:00<?, ?B/s]

data/train-00012-of-00028.parquet:   0%|          | 0.00/467M [00:00<?, ?B/s]

data/train-00013-of-00028.parquet:   0%|          | 0.00/469M [00:00<?, ?B/s]

data/train-00014-of-00028.parquet:   0%|          | 0.00/472M [00:00<?, ?B/s]

data/train-00015-of-00028.parquet:   0%|          | 0.00/473M [00:00<?, ?B/s]

data/train-00016-of-00028.parquet:   0%|          | 0.00/466M [00:00<?, ?B/s]

data/train-00017-of-00028.parquet:   0%|          | 0.00/469M [00:00<?, ?B/s]

data/train-00018-of-00028.parquet:   0%|          | 0.00/473M [00:00<?, ?B/s]

data/train-00019-of-00028.parquet:   0%|          | 0.00/469M [00:00<?, ?B/s]

data/train-00020-of-00028.parquet:   0%|          | 0.00/472M [00:00<?, ?B/s]

data/train-00021-of-00028.parquet:   0%|          | 0.00/475M [00:00<?, ?B/s]

data/train-00022-of-00028.parquet:   0%|          | 0.00/472M [00:00<?, ?B/s]

data/train-00023-of-00028.parquet:   0%|          | 0.00/476M [00:00<?, ?B/s]

data/train-00024-of-00028.parquet:   0%|          | 0.00/479M [00:00<?, ?B/s]

data/train-00025-of-00028.parquet:   0%|          | 0.00/473M [00:00<?, ?B/s]

data/train-00026-of-00028.parquet:   0%|          | 0.00/477M [00:00<?, ?B/s]

data/train-00027-of-00028.parquet:   0%|          | 0.00/473M [00:00<?, ?B/s]

data/validation-00000-of-00004.parquet:   0%|          | 0.00/411M [00:00<?, ?B/s]

data/validation-00001-of-00004.parquet:   0%|          | 0.00/410M [00:00<?, ?B/s]

data/validation-00002-of-00004.parquet:   0%|          | 0.00/412M [00:00<?, ?B/s]

data/validation-00003-of-00004.parquet:   0%|          | 0.00/412M [00:00<?, ?B/s]

data/test-00000-of-00004.parquet:   0%|          | 0.00/416M [00:00<?, ?B/s]

data/test-00001-of-00004.parquet:   0%|          | 0.00/413M [00:00<?, ?B/s]

data/test-00002-of-00004.parquet:   0%|          | 0.00/418M [00:00<?, ?B/s]

data/test-00003-of-00004.parquet:   0%|          | 0.00/409M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/82881 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10361 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/10361 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/27 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 82881
    })
    validation: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
    test: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
})

In [ ]:
train_subset = dataset["train"].shuffle(seed=42).select(range(5000))

print(train_subset)
print(train_subset[0])

Dataset({
    features: ['audio', 'duration', 'text', 'dataset_source'],
    num_rows: 5000
})
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x77feabbc94c0>, 'duration': 2.4826984127, 'text': 'من أكتر من عشرون سنة خرجت واحدة اسمها سوزان ووكر', 'dataset_source': 'egyptian-arabic-lines'}

In [ ]:
print(dataset)
print("\nTrain columns:", dataset["train"].column_names)
print("\nValidation columns:", dataset["validation"].column_names if "validation" in dataset else "No validation split")
print("\nFirst train sample:")
print(dataset["train"][0])

DatasetDict({
    train: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 82881
    })
    validation: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
    test: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
})

Train columns: ['audio', 'duration', 'text', 'dataset_source']

Validation columns: ['audio', 'duration', 'text', 'dataset_source']

First train sample:
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x77feabe41100>, 'duration': 2.6133106576, 'text': 'وبعد كدا يبص للجلاد ويقوله مقولته الشهيرة', 'dataset_source': 'egyptian-arabic-lines'}

In [ ]:
from datasets import concatenate_datasets

big_train = train_subset
big_valid = dataset["validation"] if "validation" in dataset else None

# Rename text column if needed in the big dataset
if "sentence" in big_train.column_names:
    big_train = big_train.rename_column("sentence", "text")
    if big_valid is not None:
        big_valid = big_valid.rename_column("sentence", "text")

if "transcript" in big_train.column_names:
    big_train = big_train.rename_column("transcript", "text")
    if big_valid is not None:
        big_valid = big_valid.rename_column("transcript", "text")

# Keep only the needed columns
big_train = big_train.select_columns(["audio", "text"])
if big_valid is not None:
    big_valid = big_valid.select_columns(["audio", "text"])

voice_train = voice_ds["train"].select_columns(["audio", "text"])
voice_valid = voice_ds["validation"].select_columns(["audio", "text"])

train_merged = concatenate_datasets([big_train, voice_train])

if big_valid is not None:
    valid_merged = concatenate_datasets([big_valid, voice_valid])
else:
    valid_merged = voice_valid

print("Merged train size:", len(train_merged))
print("Merged validation size:", len(valid_merged))

print("\nMerged train columns:", train_merged.column_names)
print("\nSample merged train item:")
print(train_merged[0])

Merged train size: 5060
Merged validation size: 10372

Merged train columns: ['audio', 'text']

Sample merged train item:
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x77fea9d397f0>, 'text': 'من أكتر من عشرون سنة خرجت واحدة اسمها سوزان ووكر'}

In [ ]:
from transformers import WhisperProcessor

MODEL_NAME = "openai/whisper-small"

processor = WhisperProcessor.from_pretrained(
    MODEL_NAME,
    language="ar",
    task="transcribe"
)

print("Loaded processor for:", MODEL_NAME)

preprocessor_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Loaded processor for: openai/whisper-small

In [ ]:
sample = train_merged[0]

audio = sample["audio"]
text = sample["text"]

audio_array = audio["array"]
sampling_rate = audio["sampling_rate"]

input_features = processor.feature_extractor(
    audio_array,
    sampling_rate=sampling_rate
).input_features[0]

labels = processor.tokenizer(text).input_ids

print("Text:", text)
print("Sampling rate:", sampling_rate)
print("Input feature length:", len(input_features))
print("Label length:", len(labels))
print("First 10 label ids:", labels[:10])

Text: من أكتر من عشرون سنة خرجت واحدة اسمها سوزان ووكر
Sampling rate: 16000
Input feature length: 80
Label length: 33
First 10 label ids: [50258, 50272, 50359, 50363, 27842, 5551, 4117, 2655, 2288, 9154]

In [ ]:
valid_small = valid_merged.shuffle(seed=42).select(range(300))

print("Train size:", len(train_merged))
print("Validation small size:", len(valid_small))

Train size: 5060
Validation small size: 300

In [ ]:
def prepare_example(batch):
    audio = batch["audio"]

    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    ).input_features[0]

    batch["labels"] = processor.tokenizer(batch["text"]).input_ids
    return batch

train_prepared = train_merged.map(
    prepare_example,
    remove_columns=train_merged.column_names
)

valid_prepared = valid_small.map(
    prepare_example,
    remove_columns=valid_small.column_names
)

print(train_prepared)
print(valid_prepared)
print("\nPrepared sample:")
print(train_prepared[0].keys())
print("Input feature length:", len(train_prepared[0]["input_features"]))
print("Label length:", len(train_prepared[0]["labels"]))

Map:   0%|          | 0/5060 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

Dataset({
    features: ['input_features', 'labels'],
    num_rows: 5060
})
Dataset({
    features: ['input_features', 'labels'],
    num_rows: 300
})

Prepared sample:
dict_keys(['input_features', 'labels'])
Input feature length: 80
Label length: 33

In [ ]:
from transformers import WhisperForConditionalGeneration

model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME)

model.config.forced_decoder_ids = None
model.config.suppress_tokens = []

print("Model loaded:", MODEL_NAME)

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

Model loaded: openai/whisper-small

In [ ]:
import evaluate

wer_metric = evaluate.load("wer")

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics(pred):

    pred_ids = pred.predictions
    label_ids = pred.label_ids

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer}

In [ ]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./whisper-egyptian",

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    gradient_accumulation_steps=2,

    learning_rate=1e-5,
    warmup_steps=100,

    max_steps=1500,

    eval_strategy="steps",
    eval_steps=200,

    save_strategy="steps",
    save_steps=200,
    logging_steps=25,

    fp16=True,

    predict_with_generate=True,

    generation_max_length=225,

    save_total_limit=2,

    gradient_checkpointing=True,

    report_to="none"
)

print("Training args ready")

Training args ready

In [ ]:
from pathlib import Path
from transformers import Seq2SeqTrainingArguments

CHECKPOINT_DIR = "/content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small"

Path(CHECKPOINT_DIR).mkdir(parents=True, exist_ok=True)

training_args = Seq2SeqTrainingArguments(
    output_dir=CHECKPOINT_DIR,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,

    learning_rate=1e-5,
    warmup_steps=100,
    max_steps=1500,

    eval_strategy="steps",
    eval_steps=200,

    save_strategy="steps",
    save_steps=200,
    save_total_limit=2,

    logging_steps=25,

    fp16=True,
    gradient_checkpointing=True,

    predict_with_generate=True,
    generation_max_length=225,

    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,

    report_to="none"
)

print("Training args ready")
print("Checkpoint directory:", CHECKPOINT_DIR)

Training args ready
Checkpoint directory: /content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small

In [ ]:
import torch

class DataCollatorSpeechSeq2SeqWithPadding:

    def __init__(self, processor):
        self.processor = processor

    def __call__(self, features):
        input_features = [{"input_features": f["input_features"]} for f in features]
        label_features = [{"input_ids": f["labels"]} for f in features]

        batch = self.processor.feature_extractor.pad(
            input_features,
            return_tensors="pt"
        )

        labels_batch = self.processor.tokenizer.pad(
            label_features,
            return_tensors="pt"
        )

        labels = labels_batch["input_ids"].masked_fill(
            labels_batch.attention_mask.ne(1), -100
        )

        batch["labels"] = labels
        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor)

print("Data collator ready")

Data collator ready

In [ ]:
!pip install -q peft

In [ ]:
from pathlib import Path
from transformers import Seq2SeqTrainingArguments

LORA_CHECKPOINT_DIR = "/content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora"

Path(LORA_CHECKPOINT_DIR).mkdir(parents=True, exist_ok=True)

training_args = Seq2SeqTrainingArguments(
    output_dir=LORA_CHECKPOINT_DIR,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,

    learning_rate=1e-4,
    warmup_steps=50,

    max_steps=1200,

    eval_strategy="steps",
    eval_steps=200,

    save_strategy="steps",
    save_steps=200,
    save_total_limit=2,

    logging_steps=25,

    fp16=True,
    gradient_checkpointing=True,

    predict_with_generate=True,
    generation_max_length=225,

    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,

    report_to="none"
)

print("LoRA training args ready")
print("Checkpoint directory:", LORA_CHECKPOINT_DIR)

LoRA training args ready
Checkpoint directory: /content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora

In [ ]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=train_prepared,
    eval_dataset=valid_prepared,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("LoRA trainer ready")

LoRA trainer ready

In [ ]:
import os
from transformers.trainer_utils import get_last_checkpoint

last_checkpoint = None
if os.path.isdir(training_args.output_dir):
    last_checkpoint = get_last_checkpoint(training_args.output_dir)

print("Last checkpoint:", last_checkpoint)
تمام اعمل الخطوات اللي هتقللي wer دا وهل هنرجع نمرن الموديل من جديد ؟؟
train_result = trainer.train(resume_from_checkpoint=last_checkpoint)

print("Training finished")

Last checkpoint: None

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

Training finished

In [ ]:
import re

def normalize_arabic(text):

    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub("ة", "ه", text)

    text = re.sub("[ًٌٍَُِّْـ]", "", text)

    text = re.sub("[^؀-ۿ ]+", "", text)

    text = re.sub("\s+", " ", text).strip()

    return text

<>:15: SyntaxWarning: invalid escape sequence '\s'
<>:15: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_1428/2305215111.py:15: SyntaxWarning: invalid escape sequence '\s'
  text = re.sub("\s+", " ", text).strip()

In [ ]:
cer_metric = evaluate.load("cer")

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics(pred):

    pred_ids = pred.predictions
    label_ids = pred.label_ids

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = processor.tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    pred_str = [normalize_arabic(s) for s in pred_str]
    label_str = [normalize_arabic(s) for s in label_str]

    wer = wer_metric.compute(predictions=pred_str, references=label_str)
    cer = cer_metric.compute(predictions=pred_str, references=label_str)

    return {
        "wer": wer,
        "cer": cer
    }

In [ ]:
!pip install -q librosa soundfile audioread

In [ ]:
import librosa

TEST_AUDIO_PATH = "/content/Recording.m4a"
print("Audio path:", TEST_AUDIO_PATH)

audio_array, sampling_rate = librosa.load(
    TEST_AUDIO_PATH,
    sr=16000,
    mono=True
)

duration_sec = len(audio_array) / sampling_rate

print("Sampling rate:", sampling_rate)
print("Audio shape:", audio_array.shape)
print("Duration (sec):", round(duration_sec, 2))
print("Ready for model:", sampling_rate == 16000)

Audio path: /content/Recording.m4a

/tmp/ipykernel_1428/1478503223.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sampling_rate = librosa.load(
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

Sampling rate: 16000
Audio shape: (205824,)
Duration (sec): 12.86
Ready for model: True

In [ ]:
import torch
from transformers import WhisperProcessor, WhisperForConditionalGeneration
from peft import PeftModel

MODEL_NAME = "openai/whisper-small"
ADAPTER_PATH = "/content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora/checkpoint-1200"

processor = WhisperProcessor.from_pretrained(
    MODEL_NAME,
    language="ar",
    task="transcribe"
)

base_model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME)
base_model.generation_config.forced_decoder_ids = None
base_model.generation_config.suppress_tokens = []

model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model = model.to("cuda" if torch.cuda.is_available() else "cpu")
model.eval()

print("Model and adapter loaded successfully")

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

Model and adapter loaded successfully

In [ ]:
import torch
import librosa

TEST_AUDIO_PATH = "/content/Recording.mp3"

audio_array, sampling_rate = librosa.load(TEST_AUDIO_PATH, sr=16000, mono=True)

input_features = processor.feature_extractor(
    audio_array,
    sampling_rate=16000,
    return_tensors="pt"
).input_features.to(model.device)

forced_decoder_ids = processor.get_decoder_prompt_ids(
    language="ar",
    task="transcribe"
)

with torch.no_grad():
    predicted_ids = model.generate(
        input_features=input_features,
        forced_decoder_ids=forced_decoder_ids,
        max_new_tokens=225
    )

transcription = processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True
)[0]

print("Transcription:")
print(transcription)

Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Transcription:
ه السلام عليكم أنا شهد كلية هندسة قسم كهربابة ور

In [ ]:
from datasets import concatenate_datasets

big_train_chunk_2 = dataset["train"].shuffle(seed=42).select(range(5000, 10000))
big_train_chunk_2 = big_train_chunk_2.select_columns(["audio", "text"])

voice_train = voice_ds["train"].select_columns(["audio", "text"])

train_merged_2 = concatenate_datasets([big_train_chunk_2, voice_train])

print("New merged train size:", len(train_merged_2))
print(train_merged_2[0])

New merged train size: 5060
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x77f929ce2e70>, 'text': 'قواعد بتوع التعليم نفس القصة'}

In [ ]:
train_prepared_2 = train_merged_2.map(
    prepare_example,
    remove_columns=train_merged_2.column_names
)

print(train_prepared_2)
print(train_prepared_2[0].keys())

Map:   0%|          | 0/5060 [00:00<?, ? examples/s]

Dataset({
    features: ['input_features', 'labels'],
    num_rows: 5060
})
dict_keys(['input_features', 'labels'])

In [ ]:
trainer.train_dataset = train_prepared_2
print("Trainer train dataset updated")

Trainer train dataset updated

In [ ]:
training_args.max_steps = 2000

print("New max steps:", training_args.max_steps)

New max steps: 2000

In [ ]:
import os
from transformers.trainer_utils import get_last_checkpoint

last_checkpoint = None
if os.path.isdir(training_args.output_dir):
    last_checkpoint = get_last_checkpoint(training_args.output_dir)

print("Last checkpoint:", last_checkpoint)

trainer.train(resume_from_checkpoint=last_checkpoint)

print("Training finished")

Last checkpoint: /content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora/checkpoint-1201

In [ ]:
import torch
import librosa

TEST_AUDIO_PATH = "/content/test.mp3"

audio_array, sampling_rate = librosa.load(TEST_AUDIO_PATH, sr=16000, mono=True)

input_features = processor.feature_extractor(
    audio_array,
    sampling_rate=16000,
    return_tensors="pt"
).input_features.to(model.device)

forced_decoder_ids = processor.get_decoder_prompt_ids(
    language="ar",
    task="transcribe"
)

with torch.no_grad():
    predicted_ids = model.generate(
        input_features=input_features,
        forced_decoder_ids=forced_decoder_ids,
        max_new_tokens=225
    )

transcription = processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True
)[0]

print("Transcription:")
print(transcription)

/tmp/ipykernel_168/1209765880.py:6: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sampling_rate = librosa.load(TEST_AUDIO_PATH, sr=16000, mono=True)
/usr/local/lib/python3.12/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

FileNotFoundError: [Errno 2] No such file or directory: '/content/test.mp3'

## TEST

In [13]:
!pip install -q datasets evaluate jiwer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 51.3 MB/s eta 0:00:00

In [14]:
from datasets import load_dataset

dataset = load_dataset("MAdel121/arabic-egy-cleaned")

print(dataset)
print("Splits:", dataset.keys())
print("Test size:", len(dataset["test"]))
print("Columns:", dataset["test"].column_names)

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/28 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/27 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 82881
    })
    validation: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
    test: Dataset({
        features: ['audio', 'duration', 'text', 'dataset_source'],
        num_rows: 10361
    })
})
Splits: dict_keys(['train', 'validation', 'test'])
Test size: 10361
Columns: ['audio', 'duration', 'text', 'dataset_source']

In [15]:
NUM_SAMPLES = 300
SEED = 42

test_dataset = dataset["test"].shuffle(seed=SEED).select(range(NUM_SAMPLES))

print(test_dataset)
print(test_dataset[0])

Dataset({
    features: ['audio', 'duration', 'text', 'dataset_source'],
    num_rows: 300
})
{'audio': <datasets.features._torchcodec.AudioDecoder object at 0x7e340d70fa10>, 'duration': 2.5729931972999998, 'text': 'أكتر من ثلاثون مش عارف قد إيه بالظبط', 'dataset_source': 'egyptian-arabic-lines'}

In [16]:
import re

def normalize_arabic_text(text):
    if text is None:
        return ""

    text = str(text).strip()

    # remove tashkeel
    text = re.sub(r'[\u0617-\u061A\u064B-\u0652]', '', text)

    # normalize letters
    text = re.sub(r'[أإآٱ]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)

    # remove tatweel
    text = re.sub(r'ـ', '', text)

    # remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [18]:
!pip install -q transformers peft datasets evaluate jiwer librosa soundfile audioread

from google.colab import drive
drive.mount('/content/drive')

import re
import torch
import evaluate
from tqdm.auto import tqdm
from datasets import load_dataset
from transformers import WhisperProcessor, WhisperForConditionalGeneration
from transformers.trainer_utils import get_last_checkpoint
from peft import PeftModel

# -------------------------
# 1) Load dataset
# -------------------------
dataset = load_dataset("MAdel121/arabic-egy-cleaned")

NUM_SAMPLES = 300
SEED = 42
test_dataset = dataset["test"].shuffle(seed=SEED).select(range(NUM_SAMPLES))

print("Test sample size:", len(test_dataset))
print("Columns:", test_dataset.column_names)

# -------------------------
# 2) Find latest checkpoint
# -------------------------
CHECKPOINT_ROOT = "/content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora"
latest_checkpoint = get_last_checkpoint(CHECKPOINT_ROOT)

print("Latest checkpoint:", latest_checkpoint)

if latest_checkpoint is None:
    raise ValueError(f"No checkpoint found inside: {CHECKPOINT_ROOT}")

# -------------------------
# 3) Load processor + base model + LoRA adapter
# -------------------------
MODEL_NAME = "openai/whisper-small"
device = "cuda" if torch.cuda.is_available() else "cpu"

processor = WhisperProcessor.from_pretrained(
    MODEL_NAME,
    language="ar",
    task="transcribe"
)

base_model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME)
model = PeftModel.from_pretrained(base_model, latest_checkpoint)
model = model.to(device)
model.eval()

print("Model loaded successfully")
print("Device:", device)

# -------------------------
# 4) Text normalization
# -------------------------
def normalize_arabic_text(text):
    if text is None:
        return ""

    text = str(text).strip()

    # remove tashkeel
    text = re.sub(r'[\u0617-\u061A\u064B-\u0652]', '', text)

    # normalize common Arabic letters
    text = re.sub(r'[أإآٱ]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)

    # remove tatweel
    text = re.sub(r'ـ', '', text)

    # remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # normalize spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text
# -------------------------
# 5) Inference
# -------------------------
predictions = []
references = []

forced_decoder_ids = processor.get_decoder_prompt_ids(
    language="ar",
    task="transcribe"
)

for example in tqdm(test_dataset):
    audio = example["audio"]
    reference_text = example["text"]

    audio_array = audio["array"]
    sampling_rate = audio["sampling_rate"]

    input_features = processor.feature_extractor(
        audio_array,
        sampling_rate=sampling_rate,
        return_tensors="pt"
    ).input_features.to(device)

    with torch.no_grad():
        predicted_ids = model.generate(
            input_features=input_features,
            forced_decoder_ids=forced_decoder_ids,
            max_new_tokens=225
        )

    pred_text = processor.batch_decode(
        predicted_ids,
        skip_special_tokens=True
    )[0]

    predictions.append(normalize_arabic_text(pred_text))
    references.append(normalize_arabic_text(reference_text))

print("Inference finished on", len(predictions), "samples")

# -------------------------
# 6) Evaluation
# -------------------------
wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

wer = wer_metric.compute(predictions=predictions, references=references)
cer = cer_metric.compute(predictions=predictions, references=references)

print("\n===== FINAL REPORT =====")
print(f"Samples               : {len(predictions)}")
print(f"WER                   : {wer:.4f}")
print(f"CER                   : {cer:.4f}")
print(f"Approx Word Accuracy  : {(1 - wer) * 100:.2f}%")
print(f"Approx Char Accuracy  : {(1 - cer) * 100:.2f}%")

# -------------------------
# 7) Show a few examples
# -------------------------
for i in range(min(10, len(predictions))):
    print("=" * 100)
    print("Reference :", references[i])
    print("Prediction:", predictions[i])

Mounted at /content/drive

Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/28 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/27 [00:00<?, ?it/s]

Test sample size: 300
Columns: ['audio', 'duration', 'text', 'dataset_source']
Latest checkpoint: /content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora/checkpoint-1400

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

Model loaded successfully
Device: cuda

  0%|          | 0/300 [00:00<?, ?it/s]

Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Inference finished on 300 samples

Downloading builder script: 0.00B [00:00, ?B/s]

===== FINAL REPORT =====
Samples               : 300
WER                   : 0.6341
CER                   : 0.2943
Approx Word Accuracy  : 36.59%
Approx Char Accuracy  : 70.57%
====================================================================================================
Reference : اكتر من ثلاثون مش عارف قد ايه بالظبط
Prediction: اولا مجرد يا المس ماش عارف قد يمزق
====================================================================================================
Reference : يا نهار اسود يا بيرقصوا في الجنازه
Prediction: يا ده يا ريسو يروح مدبي ورقصف الجنازي
====================================================================================================
Reference : عايز تجيب معاك ايه من السوبر ماركت
Prediction: او اظن كتاهو كل محسل بعضه
====================================================================================================
Reference : يا اسطي عنده سبعه
Prediction: ياسته عنده سابع عام
====================================================================================================
Reference : بتتكلم في حاجه دي بقي ال
Prediction: تتكلم في حاجه اثكار
====================================================================================================
Reference : زي انك تتجنب المنبهات قبل النوم بساعتين علي الاقل
Prediction: زي انك تتجنب المنابهات قبل النوم بسعتين علي الاقل
====================================================================================================
Reference : بمواصفات معينه بتخش بتسابق عليها
Prediction: بمواصفات معيانه بتخش بتسبق عليها
====================================================================================================
Reference : انا خايف عليكم يا جماعه طيب نعمل تطبيق طيب
Prediction: انا نتفعليكوا يا جماعه تفعليك
====================================================================================================
Reference : ادويه تنقص وترجع وتروح وتيجي الحكايه اللي شاغلانا كلنا بقي
Prediction: ادويه تنقص وترجع وتروح وتجل حكايه اللي شغلنا كلنا بقي
====================================================================================================
Reference : ينافس الصين في المجال دا
Prediction: هنافه الصصين في المجال دا

In [20]:

# -------------------------
# 6) Evaluation
# -------------------------
wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

wer = wer_metric.compute(predictions=predictions, references=references)
cer = cer_metric.compute(predictions=predictions, references=references)

print("\n===== FINAL REPORT =====")
print(f"Samples               : {len(predictions)}")
print(f"WER                   : {wer:.4f}")
print(f"CER                   : {cer:.4f}")
print(f"Approx Word Accuracy  : {(1 - wer) * 100:.2f}%")
print(f"Approx Char Accuracy  : {(1 - cer) * 100:.2f}%")

# -------------------------
# 7) Show a few examples
# -------------------------
for i in range(min(10, len(predictions))):
    print("=" * 100)
    print("Reference :", references[i])
    print("Prediction:", predictions[i])

===== FINAL REPORT =====
Samples               : 13
WER                   : 0.6966
CER                   : 0.3590
Approx Word Accuracy  : 30.34%
Approx Char Accuracy  : 64.10%
====================================================================================================
Reference : اكتر من ثلاثون مش عارف قد ايه بالظبط
Prediction: اولا مجرد يا المس ماش عارف قد يمزق
====================================================================================================
Reference : يا نهار اسود يا بيرقصوا في الجنازه
Prediction: يا ده يا ريسو يروح مدبي ورقصف الجنازي
====================================================================================================
Reference : عايز تجيب معاك ايه من السوبر ماركت
Prediction: او اظن كتاهو كل محسل بعضه
====================================================================================================
Reference : يا اسطي عنده سبعه
Prediction: ياسته عنده سابع عام
====================================================================================================
Reference : بتتكلم في حاجه دي بقي ال
Prediction: تتكلم في حاجه اثكار
====================================================================================================
Reference : زي انك تتجنب المنبهات قبل النوم بساعتين علي الاقل
Prediction: زي انك تتجنب المنابهات قبل النوم بسعتين علي الاقل
====================================================================================================
Reference : بمواصفات معينه بتخش بتسابق عليها
Prediction: بمواصفات معيانه بتخش بتسبق عليها
====================================================================================================
Reference : انا خايف عليكم يا جماعه طيب نعمل تطبيق طيب
Prediction: انا نتفعليكوا يا جماعه تفعليك
====================================================================================================
Reference : ادويه تنقص وترجع وتروح وتيجي الحكايه اللي شاغلانا كلنا بقي
Prediction: ادويه تنقص وترجع وتروح وتجل حكايه اللي شغلنا كلنا بقي
====================================================================================================
Reference : ينافس الصين في المجال دا
Prediction: هنافه الصصين في المجال دا

## Test

In [ ]:
!pip install -q transformers peft librosa soundfile audioread

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
from transformers.trainer_utils import get_last_checkpoint

CHECKPOINT_ROOT = "/content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora"

latest_checkpoint = get_last_checkpoint(CHECKPOINT_ROOT)

print("Latest checkpoint:", latest_checkpoint)

Latest checkpoint: /content/drive/MyDrive/asr_checkpoints/whisper_egyptian_small_lora/checkpoint-1400

In [ ]:
import torch
from transformers import WhisperProcessor, WhisperForConditionalGeneration
from peft import PeftModel

MODEL_NAME = "openai/whisper-small"

processor = WhisperProcessor.from_pretrained(
    MODEL_NAME,
    language="ar",
    task="transcribe"
)

base_model = WhisperForConditionalGeneration.from_pretrained(MODEL_NAME)

model = PeftModel.from_pretrained(base_model, latest_checkpoint)
model = model.to("cuda" if torch.cuda.is_available() else "cpu")
model.eval()

print("Model loaded successfully")
print("Device:", model.device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

normalizer.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/479 [00:00<?, ?it/s]

generation_config.json: 0.00B [00:00, ?B/s]

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

Model loaded successfully
Device: cpu

In [ ]:
TEST_AUDIO_PATH = "/content/test.mp3"
print("Test audio path:", TEST_AUDIO_PATH)

Test audio path: /content/test.mp3

In [ ]:
import librosa

audio_array, sampling_rate = librosa.load(
    TEST_AUDIO_PATH,
    sr=16000,
    mono=True
)

duration_sec = len(audio_array) / sampling_rate

print("Sampling rate:", sampling_rate)
print("Audio shape:", audio_array.shape)
print("Duration (sec):", round(duration_sec, 2))

Sampling rate: 16000
Audio shape: (117029,)
Duration (sec): 7.31

In [ ]:
forced_decoder_ids = processor.get_decoder_prompt_ids(
    language="ar",
    task="transcribe"
)

input_features = processor.feature_extractor(
    audio_array,
    sampling_rate=16000,
    return_tensors="pt"
).input_features.to(model.device)

with torch.no_grad():
    predicted_ids = model.generate(
        input_features=input_features,
        forced_decoder_ids=forced_decoder_ids,
        max_new_tokens=225
    )

transcription = processor.batch_decode(
    predicted_ids,
    skip_special_tokens=True
)[0]

print("Transcription:")
print(transcription)

Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Both `max_new_tokens` (=225) and `max_length`(=448) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

Transcription:
أختي اسمها مريم والأطبتاعي اسمه قريشة